### ISSUE TITLE
mruby_io_test.c:159:7: error: implicit declaration of function 'mkdtemp'

### ISSUE THREAD

**Issue by katzer** [iij/mruby-io#82]
Hi,

within your tests you use `mkdtemp()`. Introduced with 3ae5fea.
That does not compile under Windows as its a posix function.
